// Code generated by "stringer -type=Command"; DO NOT EDIT.

package common

import "strconv"

const _Command_name = "WrongUninitializedSimpleDataPacketAckDataPacketCloseBothPacketServerShutdownPacketClientShutdownPacketLastEnumValue"

var _Command_index = [...]uint8{0, 18, 34, 47, 62, 82, 102, 115}

func (i Command) String() string {
	if i < 0 || i >= Command(len(_Command_index)-1) {
		return "Command(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Command_name[_Command_index[i]:_Command_index[i+1]]
}
